<script setup lang="ts">
import { computed, nextTick, toRef, useTemplateRef, watch } from "vue";
import { Info } from "lucide-vue-next";
import "photoswipe/dist/photoswipe.css";
import type { FileNode } from "../types";
import { usePhotoSwipe } from "../composables/usePhotoSwipe";

const props = defineProps<{
  items: FileNode[];
  currentIndex: number;
  isOpen: boolean;
  metadataOpen?: boolean;
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "indexChange", index: number): void;
  (e: "toggleMetadata"): void;
}>();

const containerRef = useTemplateRef<HTMLElement>("container");
const metadataButtonRef = useTemplateRef<HTMLButtonElement>("metadataButton");

usePhotoSwipe({
  containerRef,
  items: computed(() => props.items),
  currentIndex: toRef(props, "currentIndex"),
  isOpen: toRef(props, "isOpen"),
  photoSwipeOptions: {
    closeOnVerticalDrag: true,
    allowPanToNext: true,
    trapFocus: false,
    returnFocus: false,
  },
  thumbnailSize: 1600,
  onIndexChange: (index) => emit("indexChange", index),
  onClose: () => emit("close"),
});

watch(
  () => props.metadataOpen,
  async (isOpen, wasOpen) => {
    if (!wasOpen || isOpen) return;
    await nextTick();
    metadataButtonRef.value?.focus({ preventScroll: true });
  },
);
</script>

<template>
  <div ref="container" class="mobile-photoswipe-container" />
  <button
    v-if="!metadataOpen"
    ref="metadataButton"
    class="lightbox-floating-control lightbox-floating-control--mobile"
    :aria-label="'View image info'"
    @click.stop="emit('toggleMetadata')"
  >
    <Info :size="22" :stroke-width="2.2" />
  </button>
</template>

<style scoped lang="scss">
.mobile-photoswipe-container {
  position: fixed;
  inset: 0;
  z-index: 1;
}

.lightbox-floating-control--mobile {
  position: fixed;
  right: max(18px, env(safe-area-inset-right) + 14px);
  bottom: max(24px, env(safe-area-inset-bottom) + 12px);
  z-index: calc(var(--gallery-z-lightbox, 100000) + 1);
}
</style>

<!-- Global PhotoSwipe 5 theme overrides — not scoped since PhotoSwipe DOM is generated by the library -->
<style lang="scss">
@import "../styles/lightbox-shared";
</style>
