<script setup lang="ts">
import { ref, computed, toRef, watch } from "vue";
import "photoswipe/dist/photoswipe.css";
import type { FileNode } from "../types";
import { usePhotoSwipe } from "../composables/usePhotoSwipe";

const props = defineProps<{
  items: FileNode[];
  currentIndex: number;
  isOpen: boolean;
  metadataOpen?: boolean;
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "indexChange", index: number): void;
  (e: "toggleMetadata"): void;
}>();

const containerRef = ref<HTMLElement | null>(null);

usePhotoSwipe({
  containerRef,
  items: computed(() => props.items),
  currentIndex: toRef(props, "currentIndex"),
  isOpen: toRef(props, "isOpen"),
  photoSwipeOptions: {
    closeOnVerticalDrag: true,
    allowPanToNext: true,
  },
  thumbnailSize: 1600,
  onIndexChange: (index) => emit("indexChange", index),
  onClose: () => emit("close"),
  onRegisterUi: (_pswp) => {
    _pswp.ui!.registerElement({
      name: "metadata-info",
      order: 9,
      isButton: true,
      html: {
        isCustomSVG: true,
        inner:
          '<circle cx="12" cy="12" r="10" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 16v-4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 8h.01" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>',
        size: 24,
      },
      onInit: (el: HTMLElement) => {
        el.classList.add("pswp__button--metadata-info");
        if (props.metadataOpen) {
          el.classList.add("active");
          el.setAttribute("aria-label", "Close image info");
        } else {
          el.setAttribute("aria-label", "View image info");
        }
      },
      onClick: () => emit("toggleMetadata"),
    });
  },
  onAfterInit: () => {
    const infoBtn = document.querySelector<HTMLElement>(
      ".pswp__button--metadata-info"
    );
    if (infoBtn) {
      infoBtn.classList.remove("pswp__hide-on-close");
      const overlay = document.querySelector<HTMLElement>(".lightbox-overlay");
      if (overlay) {
        overlay.appendChild(infoBtn);
      }
    }
  },
});

// Watch metadataOpen — toggle active state and visibility on the info button
watch(() => props.metadataOpen, (isOpen) => {
  const btn = document.querySelector<HTMLElement>(
    ".pswp__button--metadata-info"
  );
  if (btn) {
    btn.classList.toggle("active", !!isOpen);
    btn.classList.toggle("hidden", !!isOpen);
    btn.setAttribute("aria-label", isOpen ? "Close image info" : "View image info");
  }
});
</script>

<template>
  <div ref="containerRef" class="mobile-photoswipe-container"></div>
</template>

<style scoped lang="scss">
.mobile-photoswipe-container {
  position: fixed;
  inset: 0;
  z-index: 1;
}
</style>

<!-- Global PhotoSwipe 5 theme overrides — not scoped since PhotoSwipe DOM is generated by the library -->
<style lang="scss">
@import '../styles/lightbox-shared';

/* Theme the PhotoSwipe background to match our dark gallery theme */
.pswp {
  --pswp-bg: #000;
  --pswp-icon-color: #fff;
  --pswp-icon-color-secondary: #a09888;
}

/* Hide PhotoSwipe's own close/zoom — we use our own overlay controls */
.pswp__button--close,
.pswp__button--zoom {
  display: none !important;
}

/* Hide top bar (counter, close) — we have our own */
.pswp__top-bar {
  opacity: 0 !important;
  pointer-events: none !important;
}
</style>
