<script setup lang="ts">
import { ref, computed, toRef } from "vue";
import "photoswipe/dist/photoswipe.css";
import type { FileNode } from "../types";
import { usePhotoSwipe } from "../composables/usePhotoSwipe";

const props = defineProps<{
  items: FileNode[];
  currentIndex: number;
  isOpen: boolean;
  // Device-specific config
  closeOnVerticalDrag: boolean;
  allowPanToNext: boolean;
  thumbnailSize: number | null; // null = full-res
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "indexChange", index: number): void;
}>();

const containerRef = ref<HTMLElement | null>(null);

usePhotoSwipe({
  containerRef,
  items: computed(() => props.items),
  currentIndex: toRef(props, "currentIndex"),
  isOpen: toRef(props, "isOpen"),
  photoSwipeOptions: {
    closeOnVerticalDrag: props.closeOnVerticalDrag,
    allowPanToNext: props.allowPanToNext,
  },
  thumbnailSize: props.thumbnailSize,
  onIndexChange: (index) => emit("indexChange", index),
  onClose: () => emit("close"),
});
</script>

<template>
  <div ref="containerRef" class="photoswipe-container"></div>
</template>

<style scoped lang="scss">
.photoswipe-container {
  position: fixed;
  inset: 0;
  z-index: 1;
}
</style>

<!-- Global PhotoSwipe 5 theme overrides — not scoped since PhotoSwipe DOM is generated by the library -->
<style lang="scss">
@import '../styles/lightbox-shared';
</style>
