<script setup lang="ts">
import { ref, computed, toRef } from "vue";
import "photoswipe/dist/photoswipe.css";
import type { FileNode } from "../types";
import { usePhotoSwipe } from "../composables/usePhotoSwipe";

const props = defineProps<{
  items: FileNode[];
  currentIndex: number;
  isOpen: boolean;
  // Device-specific config
  closeOnVerticalDrag: boolean;
  allowPanToNext: boolean;
  thumbnailSize: number | null; // legacy prop; source policy is handled by buildPhotoSwipeItem
  paddingFn?: (
    viewportSize: { x: number; y: number },
    itemData: unknown,
    index: number,
  ) => { top: number; bottom: number; left: number; right: number };
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "indexChange", index: number): void;
}>();

const containerRef = ref<HTMLElement | null>(null);

const { loadOriginalForCurrent } = usePhotoSwipe({
  containerRef,
  items: computed(() => props.items),
  currentIndex: toRef(props, "currentIndex"),
  isOpen: toRef(props, "isOpen"),
  photoSwipeOptions: {
    closeOnVerticalDrag: props.closeOnVerticalDrag,
    allowPanToNext: props.allowPanToNext,
    ...(props.paddingFn ? { paddingFn: props.paddingFn } : {}),
  },
  thumbnailSize: props.thumbnailSize,
  onIndexChange: (index) => emit("indexChange", index),
  onClose: () => emit("close"),
  onRegisterUi: (pswp) => {
    const prevBtn = pswp.container?.querySelector(".pswp__button--arrow--prev");
    const nextBtn = pswp.container?.querySelector(".pswp__button--arrow--next");
    if (prevBtn) prevBtn.setAttribute("data-testid", "lightbox-prev");
    if (nextBtn) nextBtn.setAttribute("data-testid", "lightbox-next");
  },
});

defineExpose({
  loadOriginalForCurrent,
});
</script>

<template>
  <div
    ref="containerRef"
    class="photoswipe-container"
  />
</template>

<style scoped lang="scss">
.photoswipe-container {
  position: fixed;
  inset: 0;
  z-index: 1;
}
</style>

<!-- Global PhotoSwipe 5 theme overrides — not scoped since PhotoSwipe DOM is generated by the library -->
<style lang="scss">
@import "../styles/lightbox-shared";
</style>
