<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, computed } from "vue";
import PhotoSwipe from "photoswipe";
import "photoswipe/dist/photoswipe.css";
import type { FileNode } from "../types";
import { getImageUrl, getThumbnailUrl } from "../services/api";

const props = defineProps<{
  items: FileNode[];
  currentIndex: number;
  isOpen: boolean;
  // Device-specific config
  closeOnVerticalDrag: boolean;
  allowPanToNext: boolean;
  thumbnailSize: number | null; // null = full-res
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "indexChange", index: number): void;
}>();

const containerRef = ref<HTMLElement | null>(null);
let pswp: PhotoSwipe | null = null;

// Build PhotoSwipe data source from our items
const pswpItems = computed(() =>
  props.items.map((item) => {
    // Use full-res or thumbnail depending on config
    const src =
      props.thumbnailSize !== null
        ? getThumbnailUrl(item.path, props.thumbnailSize)
        : getImageUrl(item.path);
    return {
      src,
      width: 1200,
      height: 1600,
      alt: item.name || "",
      path: item.path,
    };
  })
);

function initPhotoSwipe() {
  if (!containerRef.value || !props.isOpen || pswp) return;

  pswp = new PhotoSwipe({
    dataSource: pswpItems.value,
    index: props.currentIndex,
    appendToEl: containerRef.value,
    closeOnVerticalDrag: props.closeOnVerticalDrag,
    allowPanToNext: props.allowPanToNext,
    showHideAnimationType: "zoom",
    wheelToZoom: false,
    bgOpacity: 1,
  });

  // Listen for index changes → emit so parent can fetch metadata
  pswp.on("change", () => {
    if (pswp) {
      emit("indexChange", pswp.currIndex);
    }
  });

  // Listen for close (swipe-down, escape key, etc.)
  pswp.on("close", () => {
    destroyPhotoSwipe();
    emit("close");
  });

  pswp.init();
}

function destroyPhotoSwipe() {
  if (pswp) {
    try {
      pswp.destroy();
    } catch (_) {
      // Already destroyed
    }
    pswp = null;
  }
}

// Watch isOpen — init when opening, destroy when closing
watch(
  () => props.isOpen,
  (open) => {
    if (open) {
      // Small delay to ensure DOM is ready
      setTimeout(() => initPhotoSwipe(), 0);
    } else {
      destroyPhotoSwipe();
    }
  }
);

// Watch currentIndex — sync PhotoSwipe if instance exists
watch(
  () => props.currentIndex,
  (index) => {
    if (pswp && pswp.currIndex !== index) {
      pswp.goTo(index);
    }
  }
);

onMounted(() => {
  if (props.isOpen) {
    initPhotoSwipe();
  }
});

onUnmounted(() => {
  destroyPhotoSwipe();
});
</script>

<template>
  <div ref="containerRef" class="photoswipe-container"></div>
</template>

<style scoped lang="scss">
.photoswipe-container {
  position: fixed;
  inset: 0;
  z-index: 1;
}
</style>

<!-- Global PhotoSwipe 5 theme overrides — not scoped since PhotoSwipe DOM is generated by the library -->
<style lang="scss">
/* Theme the PhotoSwipe background to match our dark gallery theme */
.pswp {
  --pswp-bg: #000;
}

/* Hide PhotoSwipe's own close/zoom — we use our own overlay controls */
.pswp__button--close,
.pswp__button--zoom {
  display: none !important;
}

/* Hide top bar (counter, close) — we have our own */
.pswp__top-bar {
  opacity: 0 !important;
  pointer-events: none !important;
}
</style>
